server:
  port: 80

#数据库连接池
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/book?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat,wall,log4j
    maxActive: 20
    initialSize: 5
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 500
        min-idle: 0
    timeout: 1000
resources:
  chain.strategy.content.enabled: true
  chain.strategy.content.paths: /*
  static-locations: classpath:/static/easyui/1.5.5/*,classpath:/static/jquery/*,classpath:/static/img/*,classpath:/static/platform/*
mybatis:
  mapper-locations: classpath:sqlMapperXml/*.xml
  type-aliases-package: com.book.model

mybatis-plus:
  mapper-locations: classpath:sqlMapperXml/*.xml
  type-aliases-package: com.book.model

thymeleaf:
  prefix: classpath:/templates/
  suffix: .html
  encoding: UTF-8
  cache: false
  cache-period: 0
template:
    cache: false
logging:
  level:
      org.springframework.web: Info
      com.book.mapper: debug


